///////////////////////////////////////////////////////////
//
//  ChambreNonFumeur.h
//  Implementation of the Class ChambreNonFumeur
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:28
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(ChambreNonFumeur_D044C82F_FB40_4656_8434_06C8B1417BDF__INCLUDED_)
#define ChambreNonFumeur_D044C82F_FB40_4656_8434_06C8B1417BDF__INCLUDED_


class ChambreNonFumeur
{

public:
	ChambreNonFumeur();
    ChambreNonFumeur(float volumeParam,int zoneIdParam,int idPieceParam);
    ChambreNonFumeur(float,int);
	virtual ~ChambreNonFumeur();
    float getVolume(){return volume;};
    void setIdPiece(int idPieceParam){idPiece =idPieceParam;};
    int getIdPiece(){return idPiece;};
    int getZoneId(){return zoneId;};
    void setZoneId(int zoneIdParam){zoneId=zoneIdParam;};
private:
	float volume;
	int zoneId;
    int idPiece;
};

#endif // !defined(ChambreNonFumeur_D044C82F_FB40_4656_8434_06C8B1417BDF__INCLUDED_)
