///////////////////////////////////////////////////////////
//
//  ChambreNonFumeur.cpp
//  Implementation of the Class ChambreNonFumeur
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:28
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "ChambreNonFumeur.h"

ChambreNonFumeur::ChambreNonFumeur(){

    volume = 0;
    zoneId = -1;
    idPiece = -1;
}
ChambreNonFumeur::ChambreNonFumeur(float volumeParam,int zoneIdParam,int idPieceParam){
    volume = volumeParam;
    zoneId = zoneIdParam;
    idPiece = idPieceParam;
}


ChambreNonFumeur::ChambreNonFumeur(float volumeParam,int pieceId)
{
    volume = volumeParam;
    idPiece = pieceId;
}
ChambreNonFumeur::~ChambreNonFumeur(){
    volume = 0;
    zoneId = -1;
    idPiece = -1;
}


