///////////////////////////////////////////////////////////
//
//  ChambreFumeur.h
//  Implementation of the Class ChambreFumeur
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:28
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(ChambreFumeur_45A6E174_DBA3_4373_A4FB_D9C114FFF1EE__INCLUDED_)
#define ChambreFumeur_45A6E174_DBA3_4373_A4FB_D9C114FFF1EE__INCLUDED_

#include "ZoneHotel.h"

class ChambreFumeur
{

public:
	ChambreFumeur();       
    ChambreFumeur(float,int,int);
	virtual ~ChambreFumeur();
    float getVolume(){return volume;};
    void setIdPiece(int idPieceParam){idPiece =idPieceParam;};
    int getIdPiece(){return idPiece;};
    int getZoneId(){return zoneId;};
    void setZoneId(int zoneIdParam){zoneId=zoneIdParam;};

private:
	float volume;
	int zoneId;
    int idPiece;
};

#endif // !defined(ChambreFumeur_45A6E174_DBA3_4373_A4FB_D9C114FFF1EE__INCLUDED_)
