///////////////////////////////////////////////////////////
//
//  ChambreFumeur.cpp
//  Implementation of the Class ChambreFumeur
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:28
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "ChambreFumeur.h"

ChambreFumeur::ChambreFumeur(){
    volume = 0;
    zoneId = -1;
    idPiece = -1;
}
ChambreFumeur::ChambreFumeur(float volumeParam,int zoneIdParam,int idPieceParam){
    volume = volumeParam;
    zoneId = zoneIdParam;
    idPiece = idPieceParam;
   
}


ChambreFumeur::~ChambreFumeur(){
   volume = 0;
    zoneId = -1;
    idPiece = -1; 

}


