///////////////////////////////////////////////////////////
//
//  Hotel.h
//  Implementation of the Class Hotel
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:28
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(Hotel_88C65820_450F_44fe_BB4A_8697039BC45B__INCLUDED_)
#define Hotel_88C65820_450F_44fe_BB4A_8697039BC45B__INCLUDED_

#include "Local.h"
#include "ZoneHotel.h"

class ReglementationHotel;

class Hotel : public Local
{
public:
    Hotel();
    Hotel(int,int,int);
	virtual ~Hotel();

    int getNbrChambreFumeur(){return nbrChambreFumeur;};
    int getNbrChambreNonFumeur(){return nbrChambreNonFumeur;};
    int getNbrSalleRestauration(){return nbrSalleRestauration;};
    int getNombreZonesChNonFumeur(){return nombreZonesChNonFumeur;};
    int getNombreZonesChFumeur(){return nombreZonesChFumeur;};
    int getNombreZonesSr(){return nombreZonesSr;};

    void setNombreZonesChFumeur(int nbrZonesChFumeurParam){nombreZonesChFumeur = nbrZonesChFumeurParam;};
    void setNombreZonesChNonFumeur(int nbrZonesChNonFumeurParam){nombreZonesChNonFumeur = nbrZonesChNonFumeurParam;};
    void setNombreZonesSr(int nbrZonesSrParam){nombreZonesSr = nbrZonesSrParam;};

    bool debug;

    ZoneHotel * m_ZoneHotel[21];
    ReglementationHotel * m_ReglementationHotel;

    void dm1Zone(int idZoneTab,int idPiece);
    void dm2Zone(int,int);
    void modifierZonesIdPlageDeFonctionnement();

private:
	int nbrChambreFumeur;
	int nbrChambreNonFumeur;
	int nbrSalleRestauration;
    
    int nombreZonesChFumeur;
    int nombreZonesChNonFumeur;
    int nombreZonesSr;

};

#endif // !defined(Hotel_88C65820_450F_44fe_BB4A_8697039BC45B__INCLUDED_)
