///////////////////////////////////////////////////////////
//
//  Local.h
//  Implementation of the Class Local
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:28
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(Local_6DA58E54_FE77_4a19_B5F1_C589B9A9737A__INCLUDED_)
#define Local_6DA58E54_FE77_4a19_B5F1_C589B9A9737A__INCLUDED_



class Local
{

public:
	Local();
	virtual ~Local();
    int getNombreZones(){return nombreZones;};
    int getLocalType(){return localType;};
    void setNombreZones(int nbrZonesParam){nombreZones = nbrZonesParam;};

protected:
	int nombreZones; // PART DE 0
	/**
	* identifiant locaux 0 = Hotel    1 = Bureau    2 = Enseignement
	*/
	int localType;
    
};


#endif // !defined(Local_6DA58E54_FE77_4a19_B5F1_C589B9A9737A__INCLUDED_)
