///////////////////////////////////////////////////////////
//
//  plageDeFonctionnement.h
//  Implementation of the Class plageDeFonctionnement
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:33
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(plageDeFonctionnement_36586229_08BC_4721_88D2_81AB9021B185__INCLUDED_)
#define plageDeFonctionnement_36586229_08BC_4721_88D2_81AB9021B185__INCLUDED_


class plageDeFonctionnement
{

public:
	plageDeFonctionnement();
    plageDeFonctionnement(int zoneIdParam);
    plageDeFonctionnement(int parametreHeureFin, int parametreMinFin, int parametreHeureDebut, int parametreMinDebut, bool * parametreJourDeFonctionnement);
	virtual ~plageDeFonctionnement();
    void setZoneId(zoneIdParam){zoneId = zoneIdParam;};
    void setAllJourDeFonctionnement(bool jourDeFonctionnementParam[7]);
    void setTmMinuteDebut(minuteDebutParam){tmMinuteDebut=minuteDebutParam;};
    void setTmMinuteFin(minuteFinParam){tmMinuteFin=minuteFinParam;};
    void setTmHeureDebut(heureDebutParam){tmHeureDebut=heureDebutParam;};
    void setTmHeureFin(heureFinParam){tmHeureFin=heureFinParam;};

    bool estJourDeFonctionnement(int wday) {return jourDeFonctionnement[wday];};
    bool testJourDeFonctionnement(int wday) {return jourDeFonctionnement[wday];};
    int getTmMinuteDebut(){return tmMinuteDebut;};
    int getTmMinuteFin(){return tmMinuteFin;};
    int getTmHeureDebut(){return tmHeureDebut;};
    int getTmHeureFin(){return tmHeureFin;};

private:
	bool jourDeFonctionnement[7];//0:Lundi->6:Dimanche;
	int tmMinuteDebut;
	int tmHeureDebut;
	int tmMinuteFin;
	int tmHeureFin;
    int zoneId;
};

#endif // !defined(plageDeFonctionnement_36586229_08BC_4721_88D2_81AB9021B185__INCLUDED_)
