///////////////////////////////////////////////////////////
//
//  plageDeFonctionnement.cpp
//  Implementation of the Class plageDeFonctionnement
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:33
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "plageDeFonctionnement.h"
#include "string.h"
plageDeFonctionnement::plageDeFonctionnement(){


memset(jourDeFonctionnement,false,7);
    tmMinuteDebut = 0;
    tmHeureDebut = 0;
    tmMinuteFin = 0;
    tmHeureFin = 0;
    zoneId = -1 ;
}


plageDeFonctionnement::~plageDeFonctionnement()
{

}
plageDeFonctionnement::plageDeFonctionnement(int zoneIdParam){
}


plageDeFonctionnement::plageDeFonctionnement(int parametreHeureFin,int parametreMinFin,int parametreHeureDebut,int parametreMinDebut,bool * parametreJourDeFonctionnement){

}

void plageDeFonctionnement::setAllJourDeFonctionnement(bool jourDeFonctionnementParam[7])
{
}


