///////////////////////////////////////////////////////////
//
//  SalleRestauration.h
//  Implementation of the Class SalleRestauration
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:33
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(SalleRestauration_4BFF738D_012F_4405_85C5_6221B77C566C__INCLUDED_)
#define SalleRestauration_4BFF738D_012F_4405_85C5_6221B77C566C__INCLUDED_


class SalleRestauration
{

public:
	SalleRestauration();
    SalleRestauration(float,int);
    SalleRestauration(float volumeParam,int zoneIdParam,int idPieceParam);
	virtual ~SalleRestauration();
    float getVolume(){return volume;};
    void setIdPiece(int idPieceParam){idPiece =idPieceParam;};
    int getIdPiece(){return idPiece;};
    int getZoneId(){return zoneId;};
    void setZoneId(int zoneIdParam){zoneId=zoneIdParam;};

private:
	float volume;
	int zoneId;
    int idPiece;
};

#endif // !defined(SalleRestauration_4BFF738D_012F_4405_85C5_6221B77C566C__INCLUDED_)
