///////////////////////////////////////////////////////////
//
//  TimeStamp.h
//  Implementation of the Class TimeStamp
//  Generated by Enterprise Architect
//  Created on:      10-Feb-2021 16:29:17
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(TimeStamp_A2F0731D_29F2_4864_8560_2C75FF09728A__INCLUDED_)
#define TimeStamp_A2F0731D_29F2_4864_8560_2C75FF09728A__INCLUDED_

#include <time.h>

class TimeStamp
{

public:
	TimeStamp();
	virtual ~TimeStamp();

	int getMin() {return min;};
	int getHour() {return hour;};
	int getMday() {return mday;};
	int getMon() {return mon;};
	int getYear() {return year;};
    int getWday() {return wday;};
	void setDatas();
    int getTimeStampId() {return timeStampId;};

private:
    int timeStampId;
	int min;
	int hour;
	int mday;
	int mon;
	int year;
    int wday;
};

#endif // !defined(TimeStamp_A2F0731D_29F2_4864_8560_2C75FF09728A__INCLUDED_)
