///////////////////////////////////////////////////////////
//
//  TimeStamp.cpp
//  Implementation of the Class TimeStamp
//  Generated by Enterprise Architect
//  Created on:      10-Feb-2021 16:29:17
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "TimeStamp.h"

TimeStamp::TimeStamp(){
        setDatas();
}


TimeStamp::~TimeStamp(){

}


void TimeStamp::setDatas(){
    time_t timestamp = time( NULL );
    struct tm * now = localtime( & timestamp );
    min = now->tm_min;
    hour = now->tm_hour;
	mday = now->tm_mday;
	mon = now->tm_mon+1;
	year = now->tm_year+1900;
    wday = now->tm_wday;
}


