///////////////////////////////////////////////////////////
//
//  ZoneHotel.h
//  Implementation of the Class ZoneHotel
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:34
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(ZoneHotel_818F0648_095B_417b_8F7E_6B77CD2EDA5F__INCLUDED_)
#define ZoneHotel_818F0648_095B_417b_8F7E_6B77CD2EDA5F__INCLUDED_

#include "ChambreNonFumeur.h"
#include "SalleRestauration.h"
#include "plageDeFonctionnement.h"
#include "ChambreFumeur.h"
class ChambreFumeur ;
class plageDeFonctionnement;
class ZoneHotel
{

public:
	ZoneHotel();
    ZoneHotel(int typeDeZone,int zoneIdParam);
    ZoneHotel(float volumeDeLaZone,int typeDeZone,float dm1Param,int zoneIdParam);
	virtual ~ZoneHotel();
	ChambreNonFumeur * m_ChambreNonFumeur[10];
	ChambreFumeur * m_ChambreFumeur[10];
	SalleRestauration * m_SalleRestauration;
	plageDeFonctionnement * m_plageDeFonctionnement;
	void calculerVolumeZone();
    int getZoneId(){return zoneId;};
    int getZoneType(){return zoneType;};
    int getNbrPiece(){return nbrPiece;}
    float getVolumeZone(){return volumeZone;};
    void setNbrPiece(int nbrPieceParam){nbrPiece = nbrPieceParam;};
    void setDm1(float dm1Param){dm1 = dm1Param;};
    float getDm1(){return dm1;};
    void setDm2(float dm2Param){dm2 = dm2Param;};
    void remiseAZeroMemoire(int);
    void remiseAZeroMemoireFumeur(int);
    void setZoneId(int idZone){zoneId=idZone;};
    void setZoneIdAllPiece();
    void setZoneType(int zoneTypeParam){zoneType = zoneTypeParam;};
    void setVolumeZone(float volumeZoneParam){volumeZone=volumeZoneParam;};
private:
	float volumeZone;
	/**
	* Identifiant piece CNF = 0 CF = 1 SR = 2 SH = 3 SEMPC = 4 SEL = 5 SC = 6 B = 7
	*/
	int zoneType;
	float vitesseMoteur;
    int zoneId;
	float dm1;
    float dm2;
    char adrCapteurHygrometrie;
    int nbrPiece;
};

#endif // !defined(ZoneHotel_818F0648_095B_417b_8F7E_6B77CD2EDA5F__INCLUDED_)
