///////////////////////////////////////////////////////////
//
//  ZoneHotel.cpp
//  Implementation of the Class ZoneHotel
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 13:29:34
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "ZoneHotel.h"
#include <stdio.h>
#include <string.h>

ZoneHotel::ZoneHotel(){
}
ZoneHotel::ZoneHotel(int typeDeZone,int zoneIdParam)
{
}
ZoneHotel::ZoneHotel(float volumeDeLaZone,int typeDeZone,float dm1Param,int zoneIdParam)
{
}
ZoneHotel::~ZoneHotel()
{
}


void ZoneHotel::calculerVolumeZone()
{
}

void ZoneHotel::remiseAZeroMemoire(int idPieceASupprimer)
{
}


void ZoneHotel::remiseAZeroMemoireFumeur(int idPieceASupprimer)
{
}

void ZoneHotel::setZoneIdAllPiece()
{
}






